import type { Metadata } from "next";
import localFont from "next/font/local";
import {NextIntlClientProvider} from "next-intl";
import {getLocale} from "next-intl/server";
import "./globals.scss";

const montserrat = localFont({
  src: [
    {
      path: "../fonts/Montserrat/Montserrat-VariableFont_wght.ttf",
      style: "normal",
      weight: "100 900",
    },
    {
      path: "../fonts/Montserrat/Montserrat-Italic-VariableFont_wght.ttf",
      style: "italic",
      weight: "100 900",
    },
  ],
  variable: "--font-montserrat",
  display: "swap",
});

const bebasNeue = localFont({
  src: "../fonts/Bebas_Neue/BebasNeue-Regular.ttf",
  variable: "--font-bebas-neue",
  display: "swap",
  style: "normal",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const locale = await getLocale();

  return (
    <html
      lang={locale}
      className={`${montserrat.variable} ${bebasNeue.variable}`}
    >
      <body>
        <NextIntlClientProvider>{children}</NextIntlClientProvider>
      </body>
    </html>
  );
}
